#!/usr/bin/env python3
"""Tests for research.src.lowering — lower-then-parse roundtrip."""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from research.src.contracts import Tier2Block, Tier3Slot, TypedIRExample


class TestLowering(unittest.TestCase):
    """Verify lowering produces valid DSL that roundtrips through the parser.

    Implementation-dependent: tests skip if not yet implemented.
    """

    def _make_simple_example(self):
        return TypedIRExample(
            shortcut_id="lower-test-001",
            system_prompt="",
            prompt="Show an alert",
            dsl="",  # Will be generated by lowering
            shortcut_name="TestAlert",
            tier1_tokens=["SHORTCUT", "ACTION", "ENDACTION", "ENDSHORTCUT"],
            tier2_blocks=[
                Tier2Block(
                    0,
                    "is.workflow.actions.showalert",
                    ["PARAM", "WFAlertActionMessage"],
                ),
            ],
            tier3_slots=[
                Tier3Slot("s1", "string", "Hello World", "WFAlertActionMessage"),
            ],
        )

    def test_lower_produces_endshortcut(self):
        """Lowered DSL must end with ENDSHORTCUT."""
        try:
            from research.src.lowering import lower_typed_ir_to_dsl

            example = self._make_simple_example()
            dsl = lower_typed_ir_to_dsl(example)
            self.assertTrue(dsl.strip().endswith("ENDSHORTCUT"))
        except NotImplementedError:
            self.skipTest("lower_typed_ir_to_dsl not yet implemented")

    def test_roundtrip_validate(self):
        """Lowered DSL must parse and validate successfully."""
        try:
            from research.src.lowering import roundtrip_validate

            example = self._make_simple_example()
            success, msg = roundtrip_validate(example)
            self.assertTrue(success, f"Roundtrip failed: {msg}")
        except NotImplementedError:
            self.skipTest("roundtrip_validate not yet implemented")


if __name__ == "__main__":
    unittest.main()
