#!/bin/bash
# Auto-Sign Shortcuts — watches a folder and signs new .shortcut files
# Generated by shortcuts_compiler.py
#
# SETUP:
#   1. brew install fswatch (one-time)
#   2. chmod +x auto_sign.sh
#   3. ./auto_sign.sh &  (run in background)
#   4. Drop .shortcut files into ~/Desktop/sign_inbox
#   5. Signed files appear in ~/Desktop/sign_outbox

WATCH_DIR="~/Desktop/sign_inbox"
DONE_DIR="~/Desktop/sign_outbox"
MODE="anyone"

mkdir -p "$WATCH_DIR" "$DONE_DIR"

echo "Watching $WATCH_DIR for .shortcut files..."
echo "Signed files will appear in $DONE_DIR"
echo "Press Ctrl+C to stop."

fswatch -0 "$WATCH_DIR" | while read -d "" event; do
  if [[ "$event" == *.shortcut ]] && [[ -f "$event" ]]; then
    base=$(basename "$event" .shortcut)
    outfile="$DONE_DIR/${base}_signed.shortcut"
    echo "[$(date +%H:%M:%S)] Signing: $base..."
    if shortcuts sign -i "$event" -o "$outfile" -m "$MODE" 2>/dev/null; then
      echo "[$(date +%H:%M:%S)] ✓ Signed: $outfile"
      rm "$event"
    else
      echo "[$(date +%H:%M:%S)] ✗ Failed to sign: $base"
    fi
  fi
done
